context:
  version: "3.6.4"

package:
  name: logfire-api
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/l/logfire-api/logfire_api-${{ version }}.tar.gz
    sha256: b2a3891c1112ff151bcc9274543d2ba26a8a30d40bd94c1ad3eb15fb9f4a3f08
  - url: https://raw.githubusercontent.com/pydantic/logfire/refs/heads/main/LICENSE
    sha256: 035507b8a1e787a16c7f138f092557a30a8ee9cc9cef6e84d11546ee3b9a45cd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install .

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - logfire_api
      pip_check: true

about:
  homepage: https://github.com/pydantic/logfire
  license: MIT
  license_file: LICENSE
  summary: Shim for the Logfire SDK which does nothing unless Logfire is installed

extra:
  recipe-maintainers:
    - moritzwilksch
